version: '3'

services:
  your_service:
    container_name: emulator
    # First build the image from the Dockerfile
    build:
      # Change this to where you keep above Dockerfile
      context: .
    image: "emulator"

    # Then start a container from the just built image in privileged mode to finish what's left
    entrypoint: /commands-to-run-in-privileged-mode.sh
    privileged: true