version: '3'

services:
  your_service:
    container_name: emulator
    image: "emulator"
    build:
      # Dockerfile location
      context: .

    # Run scripts in container in privileged mode
    entrypoint: /commands-to-run-in-privileged-mode.sh
    privileged: true
    env_file:
      - variables.env